FROM python:3.7-stretch

LABEL version="0.2"

WORKDIR /app
ENV FLASK_APP __init__.py
ENV FLASK_RUN_HOST 0.0.0.0
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .
ENV HOST 0.0.0.0
EXPOSE 80
CMD ["python", "python/python3_http_flaskapp.py"]
